use super::build::AddrMode;

//===========================================================================//

pub(super) const ARCH_65XX: &str = "65xx";
pub(super) const RES_65XX: &[&str] = &["A", "X", "Y"];
pub(super) const MACROS_65XX: &[(&str, &[u8], AddrMode)] = &[
    ("ADC", &[0x65], AddrMode::Addr8),
    ("ADC", &[0x75], AddrMode::Addr8CommaReg("X")),
    ("ADC", &[0x61], AddrMode::ParAddr8CommaRegEns("X")),
    ("ADC", &[0x69], AddrMode::PoundImm8),
    ("ADC", &[0x6d], AddrMode::BangAddr16),
    ("ADC", &[0x71], AddrMode::ParAddr8EnsCommaReg("Y")),
    ("ADC", &[0x79], AddrMode::BangAddr16CommaReg("Y")),
    ("ADC", &[0x7d], AddrMode::BangAddr16CommaReg("X")),
    ("AND", &[0x25], AddrMode::Addr8),
    ("AND", &[0x35], AddrMode::Addr8CommaReg("X")),
    ("AND", &[0x21], AddrMode::ParAddr8CommaRegEns("X")),
    ("AND", &[0x29], AddrMode::PoundImm8),
    ("AND", &[0x2d], AddrMode::BangAddr16),
    ("AND", &[0x31], AddrMode::ParAddr8EnsCommaReg("Y")),
    ("AND", &[0x39], AddrMode::BangAddr16CommaReg("Y")),
    ("AND", &[0x3d], AddrMode::BangAddr16CommaReg("X")),
    ("ASL", &[0x06], AddrMode::Addr8),
    ("ASL", &[0x0e], AddrMode::BangAddr16),
    ("ASL", &[0x0a], AddrMode::Reg("A")),
    ("ASL", &[0x16], AddrMode::Addr8CommaReg("X")),
    ("ASL", &[0x1e], AddrMode::BangAddr16CommaReg("X")),
    ("BCC", &[0x90], AddrMode::Relative8),
    ("BCS", &[0xb0], AddrMode::Relative8),
    ("BEQ", &[0xf0], AddrMode::Relative8),
    ("BIT", &[0x24], AddrMode::Addr8),
    ("BIT", &[0x2c], AddrMode::BangAddr16),
    ("BMI", &[0x30], AddrMode::Relative8),
    ("BNE", &[0xd0], AddrMode::Relative8),
    ("BPL", &[0x10], AddrMode::Relative8),
    ("BRK", &[0x00], AddrMode::PoundImm8),
    ("BVC", &[0x50], AddrMode::Relative8),
    ("BVS", &[0x70], AddrMode::Relative8),
    ("CLC", &[0x18], AddrMode::Implied),
    ("CLD", &[0xd8], AddrMode::Implied),
    ("CLI", &[0x58], AddrMode::Implied),
    ("CLV", &[0xb8], AddrMode::Implied),
    ("CMP", &[0xc5], AddrMode::Addr8),
    ("CMP", &[0xd5], AddrMode::Addr8CommaReg("X")),
    ("CMP", &[0xc1], AddrMode::ParAddr8CommaRegEns("X")),
    ("CMP", &[0xc9], AddrMode::PoundImm8),
    ("CMP", &[0xcd], AddrMode::BangAddr16),
    ("CMP", &[0xd1], AddrMode::ParAddr8EnsCommaReg("Y")),
    ("CMP", &[0xd9], AddrMode::BangAddr16CommaReg("Y")),
    ("CMP", &[0xdd], AddrMode::BangAddr16CommaReg("X")),
    ("CPX", &[0xe4], AddrMode::Addr8),
    ("CPX", &[0xec], AddrMode::BangAddr16),
    ("CPX", &[0xe0], AddrMode::PoundImm8),
    ("CPY", &[0xc4], AddrMode::Addr8),
    ("CPY", &[0xcc], AddrMode::BangAddr16),
    ("CPY", &[0xc0], AddrMode::PoundImm8),
    ("DEC", &[0xc6], AddrMode::Addr8),
    ("DEC", &[0xce], AddrMode::BangAddr16),
    ("DEC", &[0xd6], AddrMode::Addr8CommaReg("X")),
    ("DEC", &[0xde], AddrMode::BangAddr16CommaReg("X")),
    ("DEX", &[0xca], AddrMode::Implied),
    ("DEY", &[0x88], AddrMode::Implied),
    ("EOR", &[0x45], AddrMode::Addr8),
    ("EOR", &[0x55], AddrMode::Addr8CommaReg("X")),
    ("EOR", &[0x41], AddrMode::ParAddr8CommaRegEns("X")),
    ("EOR", &[0x49], AddrMode::PoundImm8),
    ("EOR", &[0x4d], AddrMode::BangAddr16),
    ("EOR", &[0x51], AddrMode::ParAddr8EnsCommaReg("Y")),
    ("EOR", &[0x59], AddrMode::BangAddr16CommaReg("Y")),
    ("EOR", &[0x5d], AddrMode::BangAddr16CommaReg("X")),
    ("INC", &[0xe6], AddrMode::Addr8),
    ("INC", &[0xee], AddrMode::BangAddr16),
    ("INC", &[0xf6], AddrMode::Addr8CommaReg("X")),
    ("INC", &[0xfe], AddrMode::BangAddr16CommaReg("X")),
    ("INX", &[0xe8], AddrMode::Implied),
    ("INY", &[0xc8], AddrMode::Implied),
    ("JMP", &[0x4c], AddrMode::BangAddr16),
    ("JMP", &[0x6c], AddrMode::ParBangAddr16Ens),
    ("JSR", &[0x20], AddrMode::BangAddr16),
    ("LDA", &[0xa5], AddrMode::Addr8),
    ("LDA", &[0xa1], AddrMode::ParAddr8CommaRegEns("X")),
    ("LDA", &[0xa9], AddrMode::PoundImm8),
    ("LDA", &[0xad], AddrMode::BangAddr16),
    ("LDA", &[0xb1], AddrMode::ParAddr8EnsCommaReg("Y")),
    ("LDA", &[0xb5], AddrMode::Addr8CommaReg("X")),
    ("LDA", &[0xb9], AddrMode::BangAddr16CommaReg("Y")),
    ("LDA", &[0xbd], AddrMode::BangAddr16CommaReg("X")),
    ("LDX", &[0xa6], AddrMode::Addr8),
    ("LDX", &[0xa2], AddrMode::PoundImm8),
    ("LDX", &[0xae], AddrMode::BangAddr16),
    ("LDX", &[0xb6], AddrMode::Addr8CommaReg("Y")),
    ("LDX", &[0xbe], AddrMode::BangAddr16CommaReg("Y")),
    ("LDY", &[0xa4], AddrMode::Addr8),
    ("LDY", &[0xa0], AddrMode::PoundImm8),
    ("LDY", &[0xac], AddrMode::BangAddr16),
    ("LDY", &[0xb4], AddrMode::Addr8CommaReg("X")),
    ("LDY", &[0xbc], AddrMode::BangAddr16CommaReg("X")),
    ("LSR", &[0x46], AddrMode::Addr8),
    ("LSR", &[0x4e], AddrMode::BangAddr16),
    ("LSR", &[0x4a], AddrMode::Reg("A")),
    ("LSR", &[0x56], AddrMode::Addr8CommaReg("X")),
    ("LSR", &[0x5e], AddrMode::BangAddr16CommaReg("X")),
    ("NOP", &[0xea], AddrMode::Implied),
    ("ORA", &[0x05], AddrMode::Addr8),
    ("ORA", &[0x15], AddrMode::Addr8CommaReg("X")),
    ("ORA", &[0x01], AddrMode::ParAddr8CommaRegEns("X")),
    ("ORA", &[0x09], AddrMode::PoundImm8),
    ("ORA", &[0x0d], AddrMode::BangAddr16),
    ("ORA", &[0x11], AddrMode::ParAddr8EnsCommaReg("Y")),
    ("ORA", &[0x19], AddrMode::BangAddr16CommaReg("Y")),
    ("ORA", &[0x1d], AddrMode::BangAddr16CommaReg("X")),
    ("PHA", &[0x48], AddrMode::Implied),
    ("PHP", &[0x08], AddrMode::Implied),
    ("PLA", &[0x68], AddrMode::Implied),
    ("PLP", &[0x28], AddrMode::Implied),
    ("ROL", &[0x26], AddrMode::Addr8),
    ("ROL", &[0x2a], AddrMode::Reg("A")),
    ("ROL", &[0x2e], AddrMode::BangAddr16),
    ("ROL", &[0x36], AddrMode::Addr8CommaReg("X")),
    ("ROL", &[0x3e], AddrMode::BangAddr16CommaReg("X")),
    ("ROR", &[0x66], AddrMode::Addr8),
    ("ROR", &[0x6a], AddrMode::Reg("A")),
    ("ROR", &[0x6e], AddrMode::BangAddr16),
    ("ROR", &[0x76], AddrMode::Addr8CommaReg("X")),
    ("ROR", &[0x7e], AddrMode::BangAddr16CommaReg("X")),
    ("RTI", &[0x40], AddrMode::Implied),
    ("RTS", &[0x60], AddrMode::Implied),
    ("SBC", &[0xe5], AddrMode::Addr8),
    ("SBC", &[0xf5], AddrMode::Addr8CommaReg("X")),
    ("SBC", &[0xe1], AddrMode::ParAddr8CommaRegEns("X")),
    ("SBC", &[0xe9], AddrMode::PoundImm8),
    ("SBC", &[0xed], AddrMode::BangAddr16),
    ("SBC", &[0xf1], AddrMode::ParAddr8EnsCommaReg("Y")),
    ("SBC", &[0xf9], AddrMode::BangAddr16CommaReg("Y")),
    ("SBC", &[0xfd], AddrMode::BangAddr16CommaReg("X")),
    ("SEC", &[0x38], AddrMode::Implied),
    ("SED", &[0xf8], AddrMode::Implied),
    ("SEI", &[0x78], AddrMode::Implied),
    ("STA", &[0x85], AddrMode::Addr8),
    ("STA", &[0x81], AddrMode::ParAddr8CommaRegEns("X")),
    ("STA", &[0x8d], AddrMode::BangAddr16),
    ("STA", &[0x91], AddrMode::ParAddr8EnsCommaReg("Y")),
    ("STA", &[0x95], AddrMode::Addr8CommaReg("X")),
    ("STA", &[0x99], AddrMode::BangAddr16CommaReg("Y")),
    ("STA", &[0x9d], AddrMode::BangAddr16CommaReg("X")),
    ("STX", &[0x86], AddrMode::Addr8),
    ("STX", &[0x8e], AddrMode::BangAddr16),
    ("STX", &[0x96], AddrMode::Addr8CommaReg("Y")),
    ("STY", &[0x84], AddrMode::Addr8),
    ("STY", &[0x8c], AddrMode::BangAddr16),
    ("STY", &[0x94], AddrMode::Addr8CommaReg("X")),
    ("TAX", &[0xaa], AddrMode::Implied),
    ("TAY", &[0xa8], AddrMode::Implied),
    ("TSX", &[0xba], AddrMode::Implied),
    ("TXA", &[0x8a], AddrMode::Implied),
    ("TXS", &[0x9a], AddrMode::Implied),
    ("TYA", &[0x98], AddrMode::Implied),
];

//===========================================================================//

pub(super) const ARCH_6502: &str = "6502";
pub(super) const RES_6502: &[&str] = &[];
pub(super) const MACROS_6502: &[(&str, &[u8], AddrMode)] =
    &[("JAM", &[0x02], AddrMode::Implied)];

//===========================================================================//
