use super::build::AddrMode;

//===========================================================================//

pub(super) const ARCH_SPC700: &str = "SPC700";
pub(super) const RES_SPC700: &[&str] =
    &["A", "C", "PSW", "SP", "X", "Y", "YA"];
pub(super) const MACROS_SPC700: &[(&str, u8, AddrMode)] = &[
    ("ADC", 0x84, AddrMode::RegCommaAddr8("A")),
    ("ADC", 0x85, AddrMode::RegCommaBangAddr16("A")),
    ("ADC", 0x86, AddrMode::RegCommaParRegEns("A", "X")),
    ("ADC", 0x87, AddrMode::RegCommaBracAddr8PlusRegKets("A", "X")),
    ("ADC", 0x88, AddrMode::RegCommaPoundImm8("A")),
    ("ADC", 0x89, AddrMode::Addr8CommaAddr8),
    ("ADC", 0x94, AddrMode::RegCommaAddr8PlusReg("A", "X")),
    ("ADC", 0x95, AddrMode::RegCommaBangAddr16PlusReg("A", "X")),
    ("ADC", 0x96, AddrMode::RegCommaBangAddr16PlusReg("A", "Y")),
    ("ADC", 0x97, AddrMode::RegCommaBracAddr8KetsPlusReg("A", "Y")),
    ("ADC", 0x98, AddrMode::Addr8CommaPoundImm8),
    ("ADC", 0x99, AddrMode::ParRegEnsCommaParRegEns("X", "Y")),
    ("ADDW", 0x7a, AddrMode::RegCommaAddr8("YA")),
    ("AND", 0x24, AddrMode::RegCommaAddr8("A")),
    ("AND", 0x25, AddrMode::RegCommaBangAddr16("A")),
    ("AND", 0x26, AddrMode::RegCommaParRegEns("A", "X")),
    ("AND", 0x27, AddrMode::RegCommaBracAddr8PlusRegKets("A", "X")),
    ("AND", 0x28, AddrMode::RegCommaPoundImm8("A")),
    ("AND", 0x29, AddrMode::Addr8CommaAddr8),
    ("AND", 0x34, AddrMode::RegCommaAddr8PlusReg("A", "X")),
    ("AND", 0x35, AddrMode::RegCommaBangAddr16PlusReg("A", "X")),
    ("AND", 0x36, AddrMode::RegCommaBangAddr16PlusReg("A", "Y")),
    ("AND", 0x37, AddrMode::RegCommaBracAddr8KetsPlusReg("A", "Y")),
    ("AND", 0x38, AddrMode::Addr8CommaPoundImm8),
    ("AND", 0x39, AddrMode::ParRegEnsCommaParRegEns("X", "Y")),
    // TODO: AND1 opcode
    ("ASL", 0x0b, AddrMode::Addr8),
    ("ASL", 0x0c, AddrMode::BangAddr16),
    ("ASL", 0x1b, AddrMode::Addr8PlusReg("X")),
    ("ASL", 0x1c, AddrMode::Reg("A")),
    // TODO: BBC opcode
    // TODO: BBS opcode
    ("BCC", 0x90, AddrMode::Branch),
    ("BCS", 0xb0, AddrMode::Branch),
    ("BEQ", 0xf0, AddrMode::Branch),
    ("BMI", 0x30, AddrMode::Branch),
    ("BNE", 0xd0, AddrMode::Branch),
    ("BPL", 0x10, AddrMode::Branch),
    ("BRA", 0x2f, AddrMode::Branch),
    ("BRK", 0x0f, AddrMode::Implied),
    ("BVC", 0x50, AddrMode::Branch),
    ("BVS", 0x70, AddrMode::Branch),
    ("CALL", 0x3f, AddrMode::BangAddr16),
    // TODO: CBNE opcode
    // TODO: CLR1 opcode
    ("CLRC", 0x60, AddrMode::Implied),
    ("CLRP", 0x20, AddrMode::Implied),
    ("CLRV", 0xe0, AddrMode::Implied),
    ("CMP", 0x1e, AddrMode::RegCommaBangAddr16("X")),
    ("CMP", 0x3e, AddrMode::RegCommaAddr8("X")),
    ("CMP", 0x5e, AddrMode::RegCommaBangAddr16("Y")),
    ("CMP", 0x64, AddrMode::RegCommaAddr8("A")),
    ("CMP", 0x65, AddrMode::RegCommaBangAddr16("A")),
    ("CMP", 0x66, AddrMode::RegCommaParRegEns("A", "X")),
    ("CMP", 0x67, AddrMode::RegCommaBracAddr8PlusRegKets("A", "X")),
    ("CMP", 0x68, AddrMode::RegCommaPoundImm8("A")),
    ("CMP", 0x69, AddrMode::Addr8CommaAddr8),
    ("CMP", 0x74, AddrMode::RegCommaAddr8PlusReg("A", "X")),
    ("CMP", 0x75, AddrMode::RegCommaBangAddr16PlusReg("A", "X")),
    ("CMP", 0x76, AddrMode::RegCommaBangAddr16PlusReg("A", "Y")),
    ("CMP", 0x77, AddrMode::RegCommaBracAddr8KetsPlusReg("A", "Y")),
    ("CMP", 0x78, AddrMode::Addr8CommaPoundImm8),
    ("CMP", 0x79, AddrMode::ParRegEnsCommaParRegEns("X", "Y")),
    ("CMP", 0x7e, AddrMode::RegCommaAddr8("Y")),
    ("CMP", 0xad, AddrMode::RegCommaPoundImm8("Y")),
    ("CMP", 0xc8, AddrMode::RegCommaPoundImm8("X")),
    ("CMPW", 0x5a, AddrMode::RegCommaAddr8("YA")),
    ("DAA", 0xdf, AddrMode::Reg("A")),
    ("DAS", 0xbe, AddrMode::Reg("A")),
    // TODO: DBNZ opcode
    ("DEC", 0x8b, AddrMode::Addr8),
    ("DEC", 0x1d, AddrMode::Reg("X")),
    ("DEC", 0x8c, AddrMode::BangAddr16),
    ("DEC", 0x8c, AddrMode::BangAddr16),
    ("DEC", 0x9b, AddrMode::Addr8PlusReg("X")),
    ("DEC", 0x9c, AddrMode::Reg("A")),
    ("DEC", 0xdc, AddrMode::Reg("Y")),
    ("DECW", 0x1a, AddrMode::Addr8),
    ("DI", 0xc0, AddrMode::Implied),
    ("DIV", 0x9e, AddrMode::RegCommaReg("YA", "X")),
    ("EI", 0xa0, AddrMode::Implied),
    ("EOR", 0x44, AddrMode::RegCommaAddr8("A")),
    ("EOR", 0x45, AddrMode::RegCommaBangAddr16("A")),
    ("EOR", 0x46, AddrMode::RegCommaParRegEns("A", "X")),
    ("EOR", 0x47, AddrMode::RegCommaBracAddr8PlusRegKets("A", "X")),
    ("EOR", 0x48, AddrMode::RegCommaPoundImm8("A")),
    ("EOR", 0x49, AddrMode::Addr8CommaAddr8),
    ("EOR", 0x54, AddrMode::RegCommaAddr8PlusReg("A", "X")),
    ("EOR", 0x55, AddrMode::RegCommaBangAddr16PlusReg("A", "X")),
    ("EOR", 0x56, AddrMode::RegCommaBangAddr16PlusReg("A", "Y")),
    ("EOR", 0x57, AddrMode::RegCommaBracAddr8KetsPlusReg("A", "Y")),
    ("EOR", 0x58, AddrMode::Addr8CommaPoundImm8),
    ("EOR", 0x59, AddrMode::ParRegEnsCommaParRegEns("X", "Y")),
    // TODO: EOR1 opcode
    ("INC", 0xab, AddrMode::Addr8),
    ("INC", 0x3d, AddrMode::Reg("X")),
    ("INC", 0xac, AddrMode::BangAddr16),
    ("INC", 0xbb, AddrMode::Addr8PlusReg("X")),
    ("INC", 0xbc, AddrMode::Reg("A")),
    ("INC", 0xfc, AddrMode::Reg("Y")),
    ("INCW", 0x3a, AddrMode::Addr8),
    ("JMP", 0x1f, AddrMode::BracBangAddr16PlusRegKets("X")),
    ("JMP", 0x5f, AddrMode::BangAddr16),
    ("LSR", 0x4b, AddrMode::Addr8),
    ("LSR", 0x4c, AddrMode::BangAddr16),
    ("LSR", 0x5b, AddrMode::Addr8PlusReg("X")),
    ("LSR", 0x5c, AddrMode::Reg("A")),
    ("MOV", 0xfa, AddrMode::Addr8CommaAddr8),
    ("MOV", 0x8f, AddrMode::Addr8CommaPoundImm8),
    ("MOV", 0xf8, AddrMode::RegCommaAddr8("X")),
    ("MOV", 0xeb, AddrMode::RegCommaAddr8("Y")),
    ("MOV", 0x8d, AddrMode::RegCommaPoundImm8("Y")),
    ("MOV", 0xcd, AddrMode::RegCommaPoundImm8("X")),
    ("MOV", 0xe4, AddrMode::RegCommaAddr8("A")),
    ("MOV", 0xe5, AddrMode::RegCommaBangAddr16("A")),
    ("MOV", 0xe6, AddrMode::RegCommaParRegEns("A", "X")),
    ("MOV", 0xe7, AddrMode::RegCommaBracAddr8PlusRegKets("A", "X")),
    ("MOV", 0xe8, AddrMode::RegCommaPoundImm8("A")),
    ("MOV", 0xe9, AddrMode::RegCommaBangAddr16("X")),
    ("MOV", 0xec, AddrMode::RegCommaBangAddr16("Y")),
    ("MOV", 0xf4, AddrMode::RegCommaAddr8PlusReg("A", "X")),
    ("MOV", 0xf5, AddrMode::RegCommaBangAddr16PlusReg("A", "X")),
    ("MOV", 0xf6, AddrMode::RegCommaBangAddr16PlusReg("A", "Y")),
    ("MOV", 0xf7, AddrMode::RegCommaBracAddr8KetsPlusReg("A", "Y")),
    ("MOV", 0xf9, AddrMode::RegCommaAddr8PlusReg("X", "Y")),
    ("MOV", 0xfb, AddrMode::RegCommaAddr8PlusReg("Y", "X")),
    ("MOV", 0xbf, AddrMode::RegCommaParRegEnsPlus("A", "X")),
    ("MOV", 0xc4, AddrMode::Addr8CommaReg("A")),
    ("MOV", 0xd4, AddrMode::Addr8PlusRegCommaReg("X", "A")),
    ("MOV", 0xc5, AddrMode::BangAddr16CommaReg("A")),
    ("MOV", 0xd5, AddrMode::BangAddr16PlusRegCommaReg("X", "A")),
    ("MOV", 0xd6, AddrMode::BangAddr16PlusRegCommaReg("Y", "A")),
    ("MOV", 0xc7, AddrMode::BracAddr8PlusRegKetsCommaReg("X", "A")),
    ("MOV", 0xd7, AddrMode::BracAddr8KetsPlusRegCommaReg("Y", "A")),
    ("MOV", 0xd8, AddrMode::Addr8CommaReg("X")),
    ("MOV", 0xd9, AddrMode::Addr8PlusRegCommaReg("Y", "X")),
    ("MOV", 0xc9, AddrMode::BangAddr16CommaReg("X")),
    ("MOV", 0xcb, AddrMode::Addr8CommaReg("Y")),
    ("MOV", 0xdb, AddrMode::Addr8PlusRegCommaReg("X", "Y")),
    ("MOV", 0xcc, AddrMode::BangAddr16CommaReg("Y")),
    ("MOV", 0xc6, AddrMode::ParRegEnsCommaReg("X", "A")),
    ("MOV", 0xaf, AddrMode::ParRegEnsPlusCommaReg("X", "A")),
    ("MOV", 0x5d, AddrMode::RegCommaReg("X", "A")),
    ("MOV", 0x7d, AddrMode::RegCommaReg("A", "X")),
    ("MOV", 0xfd, AddrMode::RegCommaReg("Y", "A")),
    ("MOV", 0x9d, AddrMode::RegCommaReg("X", "SP")),
    ("MOV", 0xbd, AddrMode::RegCommaReg("SP", "X")),
    ("MOV", 0xdd, AddrMode::RegCommaReg("A", "Y")),
    // TODO: MOV1 opcode
    ("MOVW", 0xba, AddrMode::RegCommaAddr8("YA")),
    ("MOVW", 0xda, AddrMode::Addr8CommaReg("YA")),
    ("MUL", 0xcf, AddrMode::Reg("YA")),
    ("NOP", 0x00, AddrMode::Implied),
    // TODO: NOT1 opcode
    ("NOTC", 0xed, AddrMode::Implied),
    ("OR", 0x04, AddrMode::RegCommaAddr8("A")),
    ("OR", 0x05, AddrMode::RegCommaBangAddr16("A")),
    ("OR", 0x06, AddrMode::RegCommaParRegEns("A", "X")),
    ("OR", 0x07, AddrMode::RegCommaBracAddr8PlusRegKets("A", "X")),
    ("OR", 0x08, AddrMode::RegCommaPoundImm8("A")),
    ("OR", 0x09, AddrMode::Addr8CommaAddr8),
    ("OR", 0x14, AddrMode::RegCommaAddr8PlusReg("A", "X")),
    ("OR", 0x15, AddrMode::RegCommaBangAddr16PlusReg("A", "X")),
    ("OR", 0x16, AddrMode::RegCommaBangAddr16PlusReg("A", "Y")),
    ("OR", 0x17, AddrMode::RegCommaBracAddr8KetsPlusReg("A", "Y")),
    ("OR", 0x18, AddrMode::Addr8CommaPoundImm8),
    ("OR", 0x19, AddrMode::ParRegEnsCommaParRegEns("X", "Y")),
    // TODO: OR1 opcode
    ("PCALL", 0x4f, AddrMode::AddrHi),
    ("POP", 0x8e, AddrMode::Reg("PSW")),
    ("POP", 0xae, AddrMode::Reg("A")),
    ("POP", 0xce, AddrMode::Reg("X")),
    ("POP", 0xee, AddrMode::Reg("Y")),
    ("PUSH", 0x0d, AddrMode::Reg("PSW")),
    ("PUSH", 0x2d, AddrMode::Reg("A")),
    ("PUSH", 0x4d, AddrMode::Reg("X")),
    ("PUSH", 0x6d, AddrMode::Reg("Y")),
    ("RET", 0x6f, AddrMode::Implied),
    ("RETI", 0x7f, AddrMode::Implied),
    ("ROL", 0x2b, AddrMode::Addr8),
    ("ROL", 0x2c, AddrMode::BangAddr16),
    ("ROL", 0x3b, AddrMode::Addr8PlusReg("X")),
    ("ROL", 0x3c, AddrMode::Reg("A")),
    ("ROR", 0x6b, AddrMode::Addr8),
    ("ROR", 0x6c, AddrMode::BangAddr16),
    ("ROR", 0x7b, AddrMode::Addr8PlusReg("X")),
    ("ROR", 0x7c, AddrMode::Reg("A")),
    ("SBC", 0xa4, AddrMode::RegCommaAddr8("A")),
    ("SBC", 0xa5, AddrMode::RegCommaBangAddr16("A")),
    ("SBC", 0xa6, AddrMode::RegCommaParRegEns("A", "X")),
    ("SBC", 0xa7, AddrMode::RegCommaBracAddr8PlusRegKets("A", "X")),
    ("SBC", 0xa8, AddrMode::RegCommaPoundImm8("A")),
    ("SBC", 0xa9, AddrMode::Addr8CommaAddr8),
    ("SBC", 0xb4, AddrMode::RegCommaAddr8PlusReg("A", "X")),
    ("SBC", 0xb5, AddrMode::RegCommaBangAddr16PlusReg("A", "X")),
    ("SBC", 0xb6, AddrMode::RegCommaBangAddr16PlusReg("A", "Y")),
    ("SBC", 0xb7, AddrMode::RegCommaBracAddr8KetsPlusReg("A", "Y")),
    ("SBC", 0xb8, AddrMode::Addr8CommaPoundImm8),
    ("SBC", 0xb9, AddrMode::ParRegEnsCommaParRegEns("X", "Y")),
    // TODO: SET1 opcode
    ("SETC", 0x80, AddrMode::Implied),
    ("SETP", 0x40, AddrMode::Implied),
    ("SLEEP", 0xef, AddrMode::Implied),
    ("STOP", 0xff, AddrMode::Implied),
    ("SUBW", 0x9a, AddrMode::RegCommaAddr8("YA")),
    // TODO: TCALL opcode
    ("TCLR1", 0x4e, AddrMode::BangAddr16),
    ("TSET1", 0x0e, AddrMode::BangAddr16),
    ("XCN", 0x9f, AddrMode::Reg("A")),
];

//===========================================================================//
